import { hasLocalPasadaWalletKey } from "../lib/auth"
import type { PasadaAccount } from "../lib/types"
import { SectionLabel } from "./ui"

/** Displays how this wallet signs without ever accepting an imported secret. */
export default function WalletSigningKeyCard({
  account,
}: {
  account: PasadaAccount
  actionLabel?: string
}) {
  const localReady = hasLocalPasadaWalletKey(account.bchAddress)
  const details =
    account.walletMode === "paytaca_walletconnect"
      ? {
          label: "Paytaca WalletConnect",
          body: "Signing approvals stay in Paytaca. PASADA never requests, receives, or stores a Paytaca recovery phrase, WIF, or private key.",
          status: "Paytaca connected",
        }
      : account.walletMode === "address_only"
        ? {
            label: "Address-only wallet",
            body: "Ownership is verified with a signed message. This mode can receive BCH and show balances, but it cannot sign escrow transactions from PASADA.",
            status: "Signing unavailable",
          }
        : {
            label: "In-app local wallet",
            body: "The signing key was generated by PASADA and remains in this browser only. Firebase stores public wallet data only.",
            status: localReady ? "Ready" : "Browser wallet needed",
          }

  return (
    <div className="mt-3 rounded-xl bg-white p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <SectionLabel>{details.label}</SectionLabel>
          <p className="mt-1 text-[11px] leading-relaxed text-ink-500">
            {details.body}
          </p>
        </div>
        <span
          className={`shrink-0 rounded-full px-2.5 py-1 font-mono text-[9px] tracking-[0.1em] uppercase ${
            account.walletMode === "address_only" ||
            (account.walletMode === "local_wallet" && !localReady)
              ? "bg-pasada-red/10 text-pasada-red"
              : "bg-pasada-blue/10 text-pasada-blue"
          }`}
        >
          {details.status}
        </span>
      </div>
    </div>
  )
}
